version: 0.0
os: linux
files:
  - source: /
    destination: /java
permissions:
  - object: /java
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: application-start-hook.sh
      timeout: 300
