version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8.x
  build:
    commands:
      - mvn clean package
artifacts:
   files:
      - '**/*'
      - SCAbuildspec.yml
      - appspec.yml
      - application-start-hook.sh
   name: myname-$(date +%Y-%m-%d) 
   discard-paths: yes
